name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          # aws-region: ap-south-1
      - name: Npm install
        run: npm install
      - name: Compile
        run: npm run build  
         # Test end-to-end by uploading two artifacts and then downloading them
      - name: Create artifact files
        run: |
          mkdir -p path/to/dir-1
          # Upload a single file artifact
      - name: 'Upload artifact #1'
        uses: actions/upload-artifact@v4
        with:
          name: 'Artifact-A'
          path: path/to/dir-1/file1.txt    
        
      # - uses: hashicorp/setup-terraform@v2
      # - name: Terraform init
      #   id: init
      #   run: terraform init
      # - name: Terraform plan
      #   id: plan
      #   run: terraform plan
      # - name: Terraform apply
      #   id: apply
      #   run: terraform apply -auto-approve -input=false
